"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 3.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path

import os

from django.contrib.messages import constants as messages

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-@cb9tptr57g_b19v)=^$bqwn1%l(tg*w#p^$)q#i*t$jds&k3u'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',

    'web_order.apps.WebOrderConfig',
    'accounts.apps.AccountsConfig',

    'django.contrib.sites',
    'allauth',
    'allauth.account',

    'django_cleanup.apps.CleanupConfig',
    'django_bootstrap5',
    'rangefilter',
    'imagekit',
    'sorl.thumbnail',
    'rest_framework',
    'widget_tweaks',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'global_login_required.GlobalLoginRequiredMiddleware',
]

ROOT_URLCONF = 'dan_main.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),
                 ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'builtins': [],
        },
    },
]

WSGI_APPLICATION = 'dan_main.wsgi.application'


# データベース設定
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'dan_main',
        'USER': 'dan_wo',
        'PASSWORD': 'weborder',
        'HOST': '',
        'PORT': '',
        'ATOMIC_REQUESTS': True,  # トランザクション関連
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'ja'

TIME_ZONE = 'Asia/Tokyo'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)

MEDIA_URL = '/media/'


INVOICE_CSV_DIR = 'invoice'
LABEL_XLS_DIR = 'label'
RAKUKON_DIR = 'rakukon'
COOK_PRODUCE_DIR = 'produce'
SALES_PRICE_DIR = 'sales'

MESSAGE_TAGS = {
    messages.ERROR: 'alert alert-danger',
    messages.WARNING: 'alert alert-warning',
    messages.SUCCESS: 'alert alert-success',
    messages.INFO: 'alert alert-info',
}

AUTH_USER_MODEL = 'accounts.User'

# django-allauthで利用するdjango.contrib.sitesを使うためにサイト識別用IDを設定
SITE_ID = 1

AUTHENTICATION_BACKENDS = (
    'allauth.account.auth_backends.AuthenticationBackend',  # 一般ユーザー用(メールアドレス認証)
    'django.contrib.auth.backends.ModelBackend',  # 管理サイト用(ユーザー名認証)
)


# 認証方法をユーザー名にする場合
ACCOUNT_AUTHENTICATION_METHOD = 'username'

# ログイン/ログアウト後の遷移先を設定
LOGIN_REDIRECT_URL = 'web_order:index'
ACCOUNT_LOGOUT_REDIRECT_URL = 'account_login'

# ログアウトリンクのクリック一発でログアウトする設定
ACCOUNT_LOGOUT_ON_GET = True

# django-allauthが送信するメールの件名に自動付与される接頭辞をブランクにする設定
ACCOUNT_EMAIL_SUBJECT_PREFIX = ''

BOOTSTRAP4 = {
    'set_placeholder': False,
}

CRISPY_TEMPLATE_PACK = 'bootstrap4'

# デフォルトのメール送信元を設定
DEFAULT_FROM_EMAIL = 'wada1@dan1.jp'

# バックアップバッチ用
BACKUP_PATH = 'backup/'
NUM_SAVED_BACKUP = 30

# 計量表出力有効単位
# 個、丁は特殊な判定があるため、ロジック上で対応
MEASURE_ENABLE_UNITS = [
    "本", "切れ", "尾", "枚", "袋"
]

# お知らせに「New」を表示する期限
NEW_COMMUNICATION_DAYS = 7

# 元旦注文画面のアレルギー最大行数
NEW_YEAR_ALLERGEN_MAX_ROWS = 30

# 盛付指示書表示期間(喫食日前)
SETOUT_FILES_VISIBLE_BEFORE_DAYS = 2

# 盛付指示書表示期間(喫食日後)
SETOUT_FILES_VISIBLE_AFTER_DAYS = 3

# 混ぜご飯計量表の1合あたりの注文数
MIX_RICE_RATE_GOU = 3

# 原体のうち、嚥下を作成する対象(部分一致、優先度は記載順)
RAW_TO_ENGE_PLATES = [
    ('うどん', True),
    ('そうめん', True),
    ('にゅうめん', True),
    ('そば', True),
    ('ラーメン', True),
    ('焼きそば ソース', True),
    ('卵焼き', False),
    ('厚焼き玉子', False),
    ('八幡巻き', False),
    ('伊達巻', False),
    ('冷やし中華スープ', False),
    ('冷やし中華', True),
]

# カルテテンプレートファイル名
KARTE_FORMAT_DOWNLOAD_NAME='施設登録用カルテ.xlsx'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


def show_toolbar(request):
    return True

DEBUG_TOOLBAR_CONFIG = {
    'SHOW_TOOLBAR_CALLBACK': show_toolbar,
}

INTERNAL_IPS = ['127.0.0.1']


# GlobalLoginRequiredMiddlewareの設定

PUBLIC_PATHS = [
    '/accounts/login/',
    '/api/units',
    '/api/orders-rate',
    '/api/gousu-rate',
    '/api/mix-rice-structure',
    '/api/gousu-log'
]

NUMBER_GROUPING = 3

DATA_UPLOAD_MAX_NUMBER_FIELDS = 10000

